# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.hostname       = "{{hostname}}"
    config.vm.box            = "{{box}}"
    config.ssh.forward_agent = true
    config.vm.network :private_network, ip: "{{ip}}"

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "3072"]
        vb.name = "{{hostname}}"
    end

    config.vm.provider :vmware_workstation do |v, override|
        v.vmx["memsize"]  = "3072"
        v.vmx["numvcpus"] = "4"
        v.gui = true
    end

    {{sync_folders}}

    provisioner = :ansible_local

    config.vm.provision provisioner do |ansible|
        ansible.limit = "all"
        ansible.become = true
        ansible.verbose = true
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "../hosts"
        ansible.galaxy_role_file = "requirements.yml"
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.galaxy_roles_path = "/etc/ansible/roles"
        ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end

    config.vm.provision :shell, inline: "echo Good job, enjoy your environment at: http://{{ip}}"
end
